#!/usr/bin/env bash

set -euo pipefail
NOTESDIR=${1}
FILTERBY=${2}
SEARCHFROMFIELD=${3}
EXTENSIONS=${4}
OPENCMD=$(envsubst -no-unset -no-empty <<<${5})
cd ${NOTESDIR}

{    rg --no-heading --no-line-number --with-filename --sort path "${FILTERBY}" -g "${EXTENSIONS}" \
  && rg --no-heading --no-line-number --with-filename --sort path "${FILTERBY}" -g "${EXTENSIONS}" \
     --files-without-match | awk '{ printf "%s:!title: %s\n", $0, $0}'; } \
  | ( [ ${FILTERBY} ] && LC_ALL=C sort -t: -k1,2 -r || cat ) \
  | ( [ ${FILTERBY} ] && LC_ALL=C sort -t: -k1,1 -u || cat )\
  | fzf --tac --no-sort -d ':' -n ${SEARCHFROMFIELD}.. \
    --preview 'bat --style=plain --color=always {1}' \
  | awk -F: "{printf \"${NOTESDIR}/%s\", \$1}" \
  | xargs -I % ${OPENCMD} %

