name: "Publish Neuron site"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v16
        with:
          name: srid
      - name: Install neuron
        run: nix profile install .
      - name: Build neuron site 🔧
        run: |
          neuron --version
          neuron -d doc/ gen --pretty-urls
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: doc/.neuron/output
          clean: true
